import type { Metadata } from "next";
import Link from "next/link";
export const metadata: Metadata = { title: "Education & Experience | Nicolas Sarmiento", description: "Nicolas Sarmiento’s education at Auburn University and experience in teaching and academic support." };
export default function Background() {
return <main className="archive-page" id="top"><div className="tech-grid"/><header className="archive-header"><nav aria-label="Background navigation"><Link href="/" className="archive-brand">NS<span>/</span></Link><Link href="/">← Home</Link><Link href="/portfolio">Projects</Link><a href="/resume.pdf" target="_blank" rel="noreferrer">Résumé ↗</a></nav></header>
<div className="archive-shell"><header className="archive-intro"><p className="archive-eyebrow">NICOLAS SARMIENTO / BACKGROUND</p><h1>Education<br/><span>&amp; experience.</span></h1><p>My studies at Auburn University and the teaching roles that have shaped how I solve problems and communicate.</p></header>
<div className="archive-layout"><aside className="archive-index"><p className="archive-eyebrow">ON THIS PAGE</p><nav aria-label="Page sections"><a href="#education">01 <span>Education</span></a><a href="#experience">02 <span>Experience</span></a></nav><Link className="archive-contact" href="/portfolio">Explore all projects ↗</Link></aside><div className="archive-content">
<section id="education"><div className="archive-section-title"><span>01</span><h2>Education</h2></div><article className="archive-timeline"><p className="archive-date">EXPECTED DECEMBER 2027 · INCOMING</p><h3>M.S. Artificial Intelligence Engineering</h3><p className="archive-organization">Auburn University · Auburn, Alabama</p><p>Incoming graduate student.</p></article><article className="archive-timeline"><p className="archive-date">EXPECTED DECEMBER 2026</p><h3>B.S. Software Engineering<br/>B.S. Aerospace Engineering</h3><p className="archive-organization">Auburn University · Auburn, Alabama</p><p>GPA: 3.65 / 4.00 · Certificate: Artificial Intelligence Engineering</p><p>Coursework includes artificial intelligence, machine learning, federated learning, data structures and algorithms, and operating systems.</p></article></section>
<section id="experience"><div className="archive-section-title"><span>02</span><h2>Work experience</h2></div><article className="archive-timeline"><p className="archive-date">AUGUST 2025 – PRESENT</p><h3>Undergraduate Teaching Assistant</h3><p className="archive-organization">Auburn University · Auburn, Alabama</p><p>Support three lab sections totaling more than 110 students in Python and MATLAB, teaching programming fundamentals, debugging, and computational problem solving.</p><p>Diagnose code errors, provide individual technical guidance, and collaborate with instructors to reinforce course concepts.</p></article><article className="archive-timeline"><p className="archive-date">SEPTEMBER 2024 – AUGUST 2025</p><h3>Academic Support Peer Tutor</h3><p className="archive-organization">Auburn University · Auburn, Alabama</p><p>Delivered more than 125 hours of one-on-one instruction to 44 students in Calculus I and II, Linear Algebra, and Differential Equations.</p><p>Earned an average rating of 4.96 / 5.00 across 51 reviews.</p></article></section>
</div></div><footer className="archive-footer"><Link href="/portfolio">← All projects</Link><a href="#top">Back to top ↑</a></footer></div></main>;
}
